site_name: kmtronic_usb_relay
site_url: https://chaitu-ycr.github.io/kmtronic_usb_relay/
site_description: "Python library for KMTronic USB Relay"
site_author: chaitu-ycr

repo_name: ""
repo_url: https://github.com/chaitu-ycr/kmtronic_usb_relay
edit_uri: blob/main/docs/

nav:
  - Overview: index.md
  - Src Manual:
    - kmtronic_usb_relay: kmtronic_usb_relay.md
    - serial_com_utils: serial_com_utils.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            show_docstring_modules: false
  - include-markdown:
      recursive: true
  - macros
  - search

theme:
  name: readthedocs
  features:
    - toc.integrate
    - search

extra_css:
  - _assets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.10.0/dist/mermaid.min.js
